### PR TITLE
Add sensor to provenance - 2 - Json Schema definition

### PR DESCRIPTION
**Pull request by niio972**
- Add json schema validation to Gson object. It allows to deserialize a dto class when this specific json schema is given

### CODE REVIEW

**Comment by colinRenaud** [comment]
In the **CustomJsonWriter** class, instead of checking if _genericEntityType_ contains the ""java.util.ArrayList" string into the **loadSchema**() method, you can pass the '_type_' variable to the method and then check if the List interface is a superclass of the given Class<T>. 
exemple : if(List.class.isAssignableFrom(type)) // instead of genericEntityType.contains("")

**Comment by colinRenaud** [comment]
Then you're not dependent of a List implementation (here the ArrayList), and it's safer since you compare Class instead of String.

**Comment by colinRenaud** [comment]
Moreover, in the **CustomJsonWriter.loadSchema**() method, i think that it's simpler to just access the last element of the _enstityDTOPath_ array instead of performing a reduction on the corresponding Stream.

**Comment by niio972** [comment]
> In the **CustomJsonWriter** class, instead of checking if _genericEntityType_ contains the ""java.util.ArrayList" string into the **loadSchema**() method, you can pass the '_type_' variable to the method and then check if the List interface is a superclass of the given Class.
> exemple : if(List.class.isAssignableFrom(type)) // instead of genericEntityType.contains("")

œ

**Comment by niio972** [comment]
Modifications done.

**Pull request merged**
